# syntax=docker/dockerfile:1

FROM nvcr.io/nvidia/pytorch:23.09-py3

# Needed for quadprog
RUN apt-get update && apt-get install -y \
  build-essential \
  && rm -rf /var/lib/apt/lists/*

ADD requirements.txt .
RUN pip install -r requirements.txt
SHELL ["/bin/bash", "--login", "-c"]
