name: syntax checking
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  check:
    name: check_syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: cclauss/Find-Python-syntax-errors-action@master